//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by xsd, Version=4.7.3062.0.
// 
namespace Plazacraft.HOMM3.DamageSymulator.Core {
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.3062.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:x-plazacraft.org:plazacraft.homm3-1.0-damagesymulator")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="urn:x-plazacraft.org:plazacraft.homm3-1.0-damagesymulator", IsNullable=false)]
    public partial class Definition {
        
        private Creatures creaturesField;
        
        private Spells spellsField;
        
        private HeroAbilities heroAbilitiesField;
        
        private SecondarySkills secondarySkillsField;
        
        private CreatureAbilities creatureAbilitiesField;
        
        private Modificators modificatorsField;
        
        /// <remarks/>
        public Creatures Creatures {
            get {
                return this.creaturesField;
            }
            set {
                this.creaturesField = value;
            }
        }
        
        /// <remarks/>
        public Spells Spells {
            get {
                return this.spellsField;
            }
            set {
                this.spellsField = value;
            }
        }
        
        /// <remarks/>
        public HeroAbilities HeroAbilities {
            get {
                return this.heroAbilitiesField;
            }
            set {
                this.heroAbilitiesField = value;
            }
        }
        
        /// <remarks/>
        public SecondarySkills SecondarySkills {
            get {
                return this.secondarySkillsField;
            }
            set {
                this.secondarySkillsField = value;
            }
        }
        
        /// <remarks/>
        public CreatureAbilities CreatureAbilities {
            get {
                return this.creatureAbilitiesField;
            }
            set {
                this.creatureAbilitiesField = value;
            }
        }
        
        /// <remarks/>
        public Modificators Modificators {
            get {
                return this.modificatorsField;
            }
            set {
                this.modificatorsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.3062.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:x-plazacraft.org:plazacraft.homm3-1.0-damagesymulator")]
    public partial class Creatures {
        
        private Creature[] itemsField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Creature")]
        public Creature[] Items {
            get {
                return this.itemsField;
            }
            set {
                this.itemsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.3062.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:x-plazacraft.org:plazacraft.homm3-1.0-damagesymulator")]
    public partial class Creature {
        
        private Reference[] itemsField;
        
        private string nameField;
        
        private Terrain[] terrainField;
        
        private int attackField;
        
        private int defenseField;
        
        private int minDamageField;
        
        private int maxDamageField;
        
        private int healthField;
        
        private int levelField;
        
        private AttackType[] attackTypeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("CreatureAbilityRef")]
        public Reference[] Items {
            get {
                return this.itemsField;
            }
            set {
                this.itemsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public Terrain[] Terrain {
            get {
                return this.terrainField;
            }
            set {
                this.terrainField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public int Attack {
            get {
                return this.attackField;
            }
            set {
                this.attackField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public int Defense {
            get {
                return this.defenseField;
            }
            set {
                this.defenseField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public int MinDamage {
            get {
                return this.minDamageField;
            }
            set {
                this.minDamageField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public int MaxDamage {
            get {
                return this.maxDamageField;
            }
            set {
                this.maxDamageField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public int Health {
            get {
                return this.healthField;
            }
            set {
                this.healthField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public int Level {
            get {
                return this.levelField;
            }
            set {
                this.levelField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public AttackType[] AttackType {
            get {
                return this.attackTypeField;
            }
            set {
                this.attackTypeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.3062.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:x-plazacraft.org:plazacraft.homm3-1.0-damagesymulator")]
    public partial class Reference {
        
        private string nameField;
        
        private string levelField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Level {
            get {
                return this.levelField;
            }
            set {
                this.levelField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.3062.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:x-plazacraft.org:plazacraft.homm3-1.0-damagesymulator")]
    public partial class Param {
        
        private string nameField;
        
        private int valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public int Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.3062.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:x-plazacraft.org:plazacraft.homm3-1.0-damagesymulator")]
    public partial class CreatureRef {
        
        private object[] itemsField;
        
        private string nameField;
        
        private int countField;
        
        private AttackType[] attackTypeField;
        
        private bool luckField;
        
        private Penalty rangePenaltyField;
        
        private Penalty obstaclePenaltyField;
        
        public CreatureRef() {
            this.luckField = false;
            this.rangePenaltyField = Penalty.None;
            this.obstaclePenaltyField = Penalty.None;
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Param", typeof(Param))]
        [System.Xml.Serialization.XmlElementAttribute("Spell", typeof(Reference))]
        public object[] Items {
            get {
                return this.itemsField;
            }
            set {
                this.itemsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public int Count {
            get {
                return this.countField;
            }
            set {
                this.countField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public AttackType[] AttackType {
            get {
                return this.attackTypeField;
            }
            set {
                this.attackTypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(false)]
        public bool Luck {
            get {
                return this.luckField;
            }
            set {
                this.luckField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(Penalty.None)]
        public Penalty RangePenalty {
            get {
                return this.rangePenaltyField;
            }
            set {
                this.rangePenaltyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(Penalty.None)]
        public Penalty ObstaclePenalty {
            get {
                return this.obstaclePenaltyField;
            }
            set {
                this.obstaclePenaltyField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.3062.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:x-plazacraft.org:plazacraft.homm3-1.0-damagesymulator")]
    public enum AttackType {
        
        /// <remarks/>
        Melee,
        
        /// <remarks/>
        Ranged,
    }
    
    /// <remarks/>
    [System.FlagsAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.3062.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:x-plazacraft.org:plazacraft.homm3-1.0-damagesymulator")]
    public enum Penalty {
        
        /// <remarks/>
        None = 1,
        
        /// <remarks/>
        value50 = 2,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.3062.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:x-plazacraft.org:plazacraft.homm3-1.0-damagesymulator")]
    public partial class Hero {
        
        private object[] itemsField;
        
        private ItemsChoiceType[] itemsElementNameField;
        
        private int attackField;
        
        private int defenseField;
        
        private int levelField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Creature", typeof(CreatureRef))]
        [System.Xml.Serialization.XmlElementAttribute("HeroAbility", typeof(Reference))]
        [System.Xml.Serialization.XmlElementAttribute("SecondarySkill", typeof(Reference))]
        [System.Xml.Serialization.XmlChoiceIdentifierAttribute("ItemsElementName")]
        public object[] Items {
            get {
                return this.itemsField;
            }
            set {
                this.itemsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ItemsElementName")]
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public ItemsChoiceType[] ItemsElementName {
            get {
                return this.itemsElementNameField;
            }
            set {
                this.itemsElementNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public int Attack {
            get {
                return this.attackField;
            }
            set {
                this.attackField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public int Defense {
            get {
                return this.defenseField;
            }
            set {
                this.defenseField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public int Level {
            get {
                return this.levelField;
            }
            set {
                this.levelField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.3062.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:x-plazacraft.org:plazacraft.homm3-1.0-damagesymulator", IncludeInSchema=false)]
    public enum ItemsChoiceType {
        
        /// <remarks/>
        Creature,
        
        /// <remarks/>
        HeroAbility,
        
        /// <remarks/>
        SecondarySkill,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.3062.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:x-plazacraft.org:plazacraft.homm3-1.0-damagesymulator")]
    public partial class Modificators {
        
        private object[] itemsField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("LevelModificator", typeof(LevelModificator))]
        [System.Xml.Serialization.XmlElementAttribute("Modificator", typeof(Modificator))]
        public object[] Items {
            get {
                return this.itemsField;
            }
            set {
                this.itemsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.3062.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:x-plazacraft.org:plazacraft.homm3-1.0-damagesymulator")]
    public partial class LevelModificator {
        
        private Level level_0Field;
        
        private Level level_1Field;
        
        private Level level_2Field;
        
        private Level level_3Field;
        
        private string nameField;
        
        private RoundType roundTypeField;
        
        public LevelModificator() {
            this.roundTypeField = RoundType.None;
        }
        
        /// <remarks/>
        public Level Level_0 {
            get {
                return this.level_0Field;
            }
            set {
                this.level_0Field = value;
            }
        }
        
        /// <remarks/>
        public Level Level_1 {
            get {
                return this.level_1Field;
            }
            set {
                this.level_1Field = value;
            }
        }
        
        /// <remarks/>
        public Level Level_2 {
            get {
                return this.level_2Field;
            }
            set {
                this.level_2Field = value;
            }
        }
        
        /// <remarks/>
        public Level Level_3 {
            get {
                return this.level_3Field;
            }
            set {
                this.level_3Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(RoundType.None)]
        public RoundType RoundType {
            get {
                return this.roundTypeField;
            }
            set {
                this.roundTypeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.3062.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:x-plazacraft.org:plazacraft.homm3-1.0-damagesymulator")]
    public partial class Level {
        
        private string valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public string Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.3062.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:x-plazacraft.org:plazacraft.homm3-1.0-damagesymulator")]
    public enum RoundType {
        
        /// <remarks/>
        None,
        
        /// <remarks/>
        Up,
        
        /// <remarks/>
        Down,
        
        /// <remarks/>
        Normal,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.3062.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:x-plazacraft.org:plazacraft.homm3-1.0-damagesymulator")]
    public partial class Modificator {
        
        private string nameField;
        
        private RoundType roundTypeField;
        
        private string valueField;
        
        public Modificator() {
            this.roundTypeField = RoundType.None;
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(RoundType.None)]
        public RoundType RoundType {
            get {
                return this.roundTypeField;
            }
            set {
                this.roundTypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public string Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.3062.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:x-plazacraft.org:plazacraft.homm3-1.0-damagesymulator")]
    public partial class CreatureAbility {
        
        private Factor[] itemsField;
        
        private string nameField;
        
        private string paramsField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Factor")]
        public Factor[] Items {
            get {
                return this.itemsField;
            }
            set {
                this.itemsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Params {
            get {
                return this.paramsField;
            }
            set {
                this.paramsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.3062.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:x-plazacraft.org:plazacraft.homm3-1.0-damagesymulator")]
    public partial class Factor {
        
        private object itemField;
        
        private FactorType[] typeField;
        
        private AttackType[] attackTypeField;
        
        private string opponentField;
        
        private string affectedField;
        
        private string creatureAbilityField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("LevelModificator", typeof(LevelModificator))]
        [System.Xml.Serialization.XmlElementAttribute("Modificator", typeof(Modificator))]
        [System.Xml.Serialization.XmlElementAttribute("ModificatorRef", typeof(Reference))]
        public object Item {
            get {
                return this.itemField;
            }
            set {
                this.itemField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public FactorType[] Type {
            get {
                return this.typeField;
            }
            set {
                this.typeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public AttackType[] AttackType {
            get {
                return this.attackTypeField;
            }
            set {
                this.attackTypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Opponent {
            get {
                return this.opponentField;
            }
            set {
                this.opponentField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Affected {
            get {
                return this.affectedField;
            }
            set {
                this.affectedField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string CreatureAbility {
            get {
                return this.creatureAbilityField;
            }
            set {
                this.creatureAbilityField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.3062.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:x-plazacraft.org:plazacraft.homm3-1.0-damagesymulator")]
    public enum FactorType {
        
        /// <remarks/>
        I0,
        
        /// <remarks/>
        I1,
        
        /// <remarks/>
        I2,
        
        /// <remarks/>
        I3,
        
        /// <remarks/>
        I4,
        
        /// <remarks/>
        I5,
        
        /// <remarks/>
        R1,
        
        /// <remarks/>
        R2,
        
        /// <remarks/>
        R3,
        
        /// <remarks/>
        R4,
        
        /// <remarks/>
        R5,
        
        /// <remarks/>
        R6,
        
        /// <remarks/>
        R7,
        
        /// <remarks/>
        R8,
        
        /// <remarks/>
        ImmuneToCreatureAbility,
        
        /// <remarks/>
        IgnoreAttack,
        
        /// <remarks/>
        IgnoreDefense,
        
        /// <remarks/>
        NoEnemyRetaliation,
        
        /// <remarks/>
        ShootsTwice,
        
        /// <remarks/>
        StrikesTwice,
        
        /// <remarks/>
        Ferocity,
        
        /// <remarks/>
        NoMeleePenalty,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.3062.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:x-plazacraft.org:plazacraft.homm3-1.0-damagesymulator")]
    public partial class CreatureAbilities {
        
        private CreatureAbility[] itemsField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("CreatureAbility")]
        public CreatureAbility[] Items {
            get {
                return this.itemsField;
            }
            set {
                this.itemsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.3062.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:x-plazacraft.org:plazacraft.homm3-1.0-damagesymulator")]
    public partial class SecondarySkill {
        
        private Factor[] itemsField;
        
        private string nameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Factor")]
        public Factor[] Items {
            get {
                return this.itemsField;
            }
            set {
                this.itemsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.3062.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:x-plazacraft.org:plazacraft.homm3-1.0-damagesymulator")]
    public partial class SecondarySkills {
        
        private SecondarySkill[] itemsField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("SecondarySkill")]
        public SecondarySkill[] Items {
            get {
                return this.itemsField;
            }
            set {
                this.itemsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.3062.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:x-plazacraft.org:plazacraft.homm3-1.0-damagesymulator")]
    public partial class HeroAbility {
        
        private Factor[] itemsField;
        
        private string nameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Factor")]
        public Factor[] Items {
            get {
                return this.itemsField;
            }
            set {
                this.itemsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.3062.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:x-plazacraft.org:plazacraft.homm3-1.0-damagesymulator")]
    public partial class HeroAbilities {
        
        private HeroAbility[] itemsField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("HeroAbility")]
        public HeroAbility[] Items {
            get {
                return this.itemsField;
            }
            set {
                this.itemsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.3062.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:x-plazacraft.org:plazacraft.homm3-1.0-damagesymulator")]
    public partial class Spell {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.3062.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:x-plazacraft.org:plazacraft.homm3-1.0-damagesymulator")]
    public partial class Spells {
        
        private Spell[] itemsField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Spell")]
        public Spell[] Items {
            get {
                return this.itemsField;
            }
            set {
                this.itemsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.3062.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:x-plazacraft.org:plazacraft.homm3-1.0-damagesymulator")]
    public enum Terrain {
        
        /// <remarks/>
        Grass,
        
        /// <remarks/>
        Snow,
        
        /// <remarks/>
        Lava,
        
        /// <remarks/>
        Subterranean,
        
        /// <remarks/>
        Dirt,
        
        /// <remarks/>
        Swamp,
        
        /// <remarks/>
        Sand,
        
        /// <remarks/>
        Rough,
        
        /// <remarks/>
        Highlands,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.3062.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:x-plazacraft.org:plazacraft.homm3-1.0-damagesymulator")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="urn:x-plazacraft.org:plazacraft.homm3-1.0-damagesymulator", IsNullable=false)]
    public partial class Fight {
        
        private Hero attackerField;
        
        private Hero defenderField;
        
        private Terrain[] terrainField;
        
        /// <remarks/>
        public Hero Attacker {
            get {
                return this.attackerField;
            }
            set {
                this.attackerField = value;
            }
        }
        
        /// <remarks/>
        public Hero Defender {
            get {
                return this.defenderField;
            }
            set {
                this.defenderField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public Terrain[] Terrain {
            get {
                return this.terrainField;
            }
            set {
                this.terrainField = value;
            }
        }
    }
}
